### ISSUE TITLE
"No connection to server!"

### ISSUE THREAD

**Issue by EDavidF** [junjunguo/PocketMaps#123]
Hi. Thanks for your work on this.
When I hit "+", it takes me to 'Download' but I get the above error every time. Tried on working WiFi and LTE.

Version 3.0 from F-Droid (location & storage permissions granted, writable to storage directory)
Android 9
Build 47.2.A.10.80
Kernel 4.4.148-perf+
Sony G8142 (Xperia XZ Premium).

Any ideas?

Thanks, again.

**Comment by Starcommander** [comment]
Hello EDavidF.
Thanks for your report.

Are the maps listed on 'Download' View? And can you download them?

Can you try to execute the maps via webbrowser on android?
http://vsrv15044.customer.xenway.de/maps/
You should see a simple webpage with the maps.
Does this work?

Maybe you can also create a logcat-output via android-debug-bridge (adb logcat) directly after trying to hit "+"
This could maybe help me to find an exception.

Thanks in advance.
Br, Paul

**Comment by Starcommander** [comment]
@EDavidF 
Maybe you can help me to find out, why this issue occurs.
See questions above.

Thanks,
Br, Paul

**Comment by Scafir** [comment]
I have the same problem, the maps via webbrowser are accessible. I installed it through F-droid if this can be any help
I will try to check the logs tonight

**Comment by Scafir** [comment]
There it is:
```
12-29 22:18:17.166  4876  4876 I am_on_resume_called: [0,com.junjunguo.pocketmaps.activities.MainActivity,RESUME_ACTIVITY]
12-29 22:18:17.221  4876  4903 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-29 22:18:17.233  4876  4903 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
12-29 22:18:18.286  4876  4876 I am_on_paused_called: [0,com.junjunguo.pocketmaps.activities.MainActivity,performPause]
12-29 22:18:18.304  4876  4876 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6f94401
12-29 22:18:18.341  4876  4876 I am_on_create_called: [0,com.junjunguo.pocketmaps.activities.DownloadMapActivity,performCreate]
12-29 22:18:18.342  4876  7854 W System.err: java.io.IOException: Cleartext HTTP traffic to vsrv15044.customer.xenway.de not permitted
12-29 22:18:18.343  4876  7854 W System.err: 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
12-29 22:18:18.343  4876  7854 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
12-29 22:18:18.343  4876  7854 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
12-29 22:18:18.343  4876  7854 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
12-29 22:18:18.344  4876  4876 I am_on_start_called: [0,com.junjunguo.pocketmaps.activities.DownloadMapActivity,handleStartActivity]
12-29 22:18:18.345  4876  7854 W System.err: 	at java.net.URL.openStream(URL.java:1072)
12-29 22:18:18.345  4876  7854 W System.err: 	at com.junjunguo.pocketmaps.downloader.DownloadFiles.downloadTextfile(DownloadFiles.java:32)
12-29 22:18:18.345  4876  7854 W System.err: 	at com.junjunguo.pocketmaps.activities.DownloadMapActivity.getMapsFromJSsources(DownloadMapActivity.java:242)
12-29 22:18:18.345  4876  7854 W System.err: 	at com.junjunguo.pocketmaps.activities.DownloadMapActivity$1.doInBackground(DownloadMapActivity.java:182)
12-29 22:18:18.345  4876  7854 W System.err: 	at com.junjunguo.pocketmaps.activities.DownloadMapActivity$1.doInBackground(DownloadMapActivity.java:156)
12-29 22:18:18.345  4876  7854 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
12-29 22:18:18.345  4876  7854 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-29 22:18:18.345  4876  7854 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
12-29 22:18:18.345  4876  7854 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-29 22:18:18.346  4876  7854 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-29 22:18:18.346  4876  4876 I am_on_resume_called: [0,com.junjunguo.pocketmaps.activities.DownloadMapActivity,RESUME_ACTIVITY]
12-29 22:18:18.346  4876  7854 W System.err: 	at java.lang.Thread.run(Thread.java:764)
12-29 22:18:18.346  4876  7854 I com.junjunguo.pocketmaps.activities.DownloadMapActivity: Json file downloaded
12-29 22:18:18.346  4876  7854 W System.err: org.json.JSONException: End of input at character 0 of 
12-29 22:18:18.348  4876  7854 W System.err: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
12-29 22:18:18.348  4876  7854 W System.err: 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
12-29 22:18:18.348  4876  7854 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:159)
12-29 22:18:18.348  4876  7854 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:176)
12-29 22:18:18.348  4876  7854 W System.err: 	at com.junjunguo.pocketmaps.activities.DownloadMapActivity.getMapsFromJSsources(DownloadMapActivity.java:245)
12-29 22:18:18.348  4876  7854 W System.err: 	at com.junjunguo.pocketmaps.activities.DownloadMapActivity$1.doInBackground(DownloadMapActivity.java:182)
12-29 22:18:18.348  4876  7854 W System.err: 	at com.junjunguo.pocketmaps.activities.DownloadMapActivity$1.doInBackground(DownloadMapActivity.java:156)
12-29 22:18:18.348  4876  7854 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
12-29 22:18:18.348  4876  7854 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-29 22:18:18.351  4876  7854 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
12-29 22:18:18.351  4876  7854 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-29 22:18:18.351  4876  7854 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-29 22:18:18.351  4876  7854 W System.err: 	at java.lang.Thread.run(Thread.java:764)
12-29 22:18:18.377  4876  4903 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE

```

Funnily enough, I am learning android development and had a similar problem. I created a pull request #124 with the necessary fixes.

**Comment by Starcommander** [comment]
@Scafir 

Many thanks for your contribution, good work!
I can not test on Android9, maps-download works on my device with Android8 (LineageOS 15.1).
But I tested the GeocoderNomitatim for searching places, and it works.
To prevent an Exception I had to include the library `conscrypt-android`.

Best regards,
Paul

**Comment by Starcommander** [comment]
Should be fixed now
