### ISSUE TITLE
3.7 crashes opening bookmarks

### ISSUE THREAD

**Issue by feelingwalnut** [junjunguo/PocketMaps#149]
I compiled the app as it is only available as source.

When i open the menu and hit the + icon the app crashes and when i am in the navigation menu and hit the star icon it crashes.
Will investigate further when there is more time.

**Comment by Starcommander** [comment]
@feelingwalnut Thanks for the report.
Seems it has to do with favourites text file.
Maybe you can get a logcat output after crash.

**Comment by feelingwalnut** [comment]
Yes, i have to wait for time to set that up again.

**Comment by feelingwalnut** [comment]
works fine in emulator-bluestacks. but not on phone.
is this related?

FATAL EXCEPTION: main
Process: com.junjunguo.pocketmaps, PID: 26405
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.junjunguo.pocketmaps.fragments.MyAddressAdapter$ViewHolder.setItemData(:68)
at com.junjunguo.pocketmaps.fragments.MyAddressAdapter.onBindViewHolder(:107)
at com.junjunguo.pocketmaps.fragments.MyAddressAdapter.onBindViewHolder(:24)
at androidx.recyclerview.widget.RecyclerView$g.onBindViewHolder(:7056)
at androidx.recyclerview.widget.RecyclerView$g.bindViewHolder(:7098)
at androidx.recyclerview.widget.RecyclerView$v.H(:6010)
at androidx.recyclerview.widget.RecyclerView$v.I(:6277)
at androidx.recyclerview.widget.RecyclerView$v.p(:6116)
at androidx.recyclerview.widget.RecyclerView$v.o(:6112)
at androidx.recyclerview.widget.LinearLayoutManager$c.d(:2303)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(:1627)
at androidx.recyclerview.widget.LinearLayoutManager.fill(:1587)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(:665)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(:4132)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(:3849)
at androidx.recyclerview.widget.RecyclerView.onLayout(:4402)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:1065)
at android.view.View.layout(View.java:23753)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3683)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3143)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2204)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9069)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
at android.view.Choreographer.doCallbacks(Choreographer.java:797)
at android.view.Choreographer.doFrame(Choreographer.java:732)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8125)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by Starcommander** [comment]
@feelingwalnut  Yes, this is related.
Seems your Favourites-File is corrupted.
Workaround: Find out, where your maps are stored.
(main_menu-->change_directory)
There is also a file: Favourites.properties
- Stop (kill) pocketmaps
- Delete this file (using a file browser)
- This should solve this error for you.

TODO: Changing source code, pocketmaps should recognize such a corrupted file.

**Comment by feelingwalnut** [comment]
That fixed it. Thank you.
I was curious how it worked fresh on an emulator but failed on my device. Thought it might be scraps from prior install.

For others, file located in:
/storage/emulated/0/Android/data/com.junjunguo.pocketmaps/files/Download/pocketmaps
